import sqlite3
conn = sqlite3.connect('bager_library.db')
cursor = conn.cursor()
# conn.execute("INSERT INTO members (member_id, phone_number) VALUES (';oiy','puihj'),('lhjk',);")
# conn.execute("CREATE TABLE members (id INTEGER PRIMARY KEY AUTOINCREMENT, member_id varchar(255) UNIQUE NOT NULL, phone_number varchar(255) NOT NULL);")
# conn.execute("ALTER TABLE loans DROP COLUMN member_id;")
# conn.execute("ALTER TABLE loans ADD member_name varchar(255);")
# conn.execute("DELETE FROM loans;")
conn.commit()
conn.close()